export function numericTableDialogForm() {
    return {
        "inline": true,
        "formEle": [
            {
                "label": "ID",
                "placeholder": "ID",
                "type": "text",
                "name": "id",
                "span": 6,
                "disabled": true
            }, {
                "label": "物品名",
                "placeholder": "物品名",
                "type": "text",
                "name": "item_name",
                "span": 6
            }, {
                "label": "物品ID",
                "placeholder": "物品ID",
                "type": "text",
                "name": "item_id",
                "span": 6
            }, {
                "label": "排序",
                "placeholder": "排序",
                "type": "text",
                "name": "item_sort",
                "span": 6
            }, {
                "row": 24
            }, {
                "label": "物品类型",
                "placeholder": "物品类型",
                "type": "select",
                "options": [{
                    value: '1',
                    label: '金币/钻石/月卡'
                }, {
                    value: '2',
                    label: '话费'
                }, {
                    value: '3',
                    label: '实物'
                }],
                "name": "item_type",
                "span": 6
            }, {
                "label": "物品积分",
                "placeholder": "物品积分",
                "type": "text",
                "name": "item_points",
                "span": 6
            }, {
                "label": "物品数量",
                "placeholder": "物品数量",
                "type": "text",
                "name": "num",
                "span": 6
            }, {
                "label": "日期",
                "placeholder": "日期",
                "type": "text",
                "name": "date",
                "span": 6
            }, {
                "row": 24
            }, {
                "label": "热门物品排序",
                "placeholder": "热门物品排序",
                "type": "text",
                "name": "hot_item_sort",
                "span": 6
            }, {
                "label": "物品icon",
                "placeholder": "物品icon",
                "type": "text",
                "name": "item_icon",
                "span": 6
            }, {
                "label": "热门icon",
                "placeholder": "热门icon",
                "type": "text",
                "name": "hot_icon",
                "span": 6
            }, {
                "label": "个人兑换日限量",
                "placeholder": "个人兑换日限量",
                "type": "text",
                "name": "day_limit",
                "span": 6
            }, {
                "row": 24
            }, {
                "label": "个人兑换总限量",
                "placeholder": "个人兑换总限量",
                "type": "text",
                "name": "all_limit",
                "span": 6,
            }, {
                "label": "全服兑换日限量",
                "placeholder": "全服兑换日限量",
                "type": "text",
                "name": "all_service_day_limit",
                "span": 6,
            }, {
                "label": "全服兑换总限量",
                "placeholder": "全服兑换总限量",
                "type": "text",
                "name": "all_service_limit",
                "span": 6,
            }, {
                "label": "是否公示",
                "placeholder": "是否公示",
                "type": "select",
                "options": [{
                    value: '0',
                    label: '不公示'
                }, {
                    value: '1',
                    label: '公示'
                }],
                "name": "is_active",
                "span": 6
            }, {
                "row": 24
            }, {
                "label": "物品名颜色",
                "placeholder": "物品名颜色",
                "type": "text",
                "name": "item_name_colour",
                "span": 6,
                "disabled": true
            }, {
                "label": "累计充值区间",
                "placeholder": "累计充值区间",
                "type": "text",
                "name": "isShow_section",
                "span": 6,
                "disabled": true
            }, {
                "label": "可见用户ID",
                "placeholder": "可见用户ID",
                "type": "text",
                "name": "isShow_userID",
                "span": 6,
                "disabled": true
            }
        ]
    }
}
