export function feedbackForm() {
    return {
        "inline": true,
        "btnSpan": 6,
        "btns": [{
            "name": "query",
            "title": "查 询",
            "valid": false
        }],
        "formEle": [{
            "label": "处理状态",
            "placeholder": "处理状态",
            "type": "select",
            "name": "IsProcessed",
            "span": 6,
            "options": [{
                value: '',
                label: '全部'
            }, {
                value: '0',
                label: '未处理'
            }, {
                value: '1',
                label: '已处理'
            }]
        }]
    }
}

export function detailDialogForm() {
    return {
        "inline": true,
        "btnSpan": 6,
        "btns": [{
            "name": "close",
            "title": "确 定",
            "valid": false
        }],
        "formEle": [{
            "label": "反馈ID",
            "placeholder": "反馈ID",
            "type": "text",
            "name": "FeedbackID",
            "span": 12,
            "disabled": true,
        }, {
            "label": "处理状态",
            "placeholder": "处理状态",
            "type": "text",
            "name": "IsProcessed",
            "span": 12,
            "disabled": true,
        }, {
            "name": "row",
            "span": 24
        }, {
            "label": "反馈内容",
            "placeholder": "反馈内容",
            "type": "textarea",
            "name": "FeedbackContent",
            "span": 24,
            "disabled": true,
        }, {
            "label": "反馈帐号",
            "placeholder": "反馈帐号",
            "type": "text",
            "name": "",
            "span": 12,
            "disabled": true,
        }, {
            "label": "手机号码",
            "placeholder": "手机号码",
            "type": "text",
            "name": "MobileNo",
            "span": 12,
            "disabled": true,
        }, {
            "name": "row",
            "span": 24
        }, {
            "label": "问题类型",
            "placeholder": "问题类型",
            "type": "text",
            "name": "QuestionType",
            "span": 12,
            "disabled": true,
        }, {
            "label": "游戏类型",
            "placeholder": "游戏类型",
            "type": "text",
            "name": "GameType",
            "span": 12,
            "disabled": true,
        }, {
            "name": "row",
            "span": 24
        }, {
            "label": "反馈日期",
            "placeholder": "反馈日期",
            "type": "text",
            "name": "FeedbackDate",
            "span": 12,
            "disabled": true,
        }, {
            "label": "反馈地址",
            "placeholder": "反馈地址",
            "type": "text",
            "name": "ClientIP",
            "span": 12,
            "disabled": true,
        }, {
            "name": "row",
            "span": 24
        }, {
            "label": "回复内容",
            "placeholder": "回复内容",
            "type": "textarea",
            "name": "RevertContent",
            "span": 24,
            "disabled": true,
        }, {
            "name": "row",
            "span": 24
        }, {
            "label": "回复人",
            "placeholder": "回复人",
            "type": "text",
            "name": "RevertUserID",
            "span": 12,
            "disabled": true,
        }, {
            "label": "回复日期",
            "placeholder": "回复日期",
            "type": "timeRange",
            "name": "RevertDate",
            "span": 12,
            "disabled": true,
        }, {
            "name": "row",
            "span": 24
        }, {
            "label": "显示状态",
            "placeholder": "显示状态",
            "type": "select",
            "name": "Nullity",
            "options": [{
                value: '1',
                label: '禁用'
            }],
            "span": 12,
            "disabled": true,
        }]
    }
}
export function handleDialogForm() {
    return {
        "inline": true,
        "btnSpan": 6,
        "btns": [{
            "name": "close",
            "title": "关 闭",
            "valid": false
        }, {
            "name": "reply",
            "title": "回 复",
            "valid": false
        }],
        "formEle": [{
            "label": "反馈ID",
            "placeholder": "反馈ID",
            "type": "text",
            "name": "FeedbackID",
            "span": 12,
            "disabled": true,
        }, {
            "label": "处理状态",
            "placeholder": "处理状态",
            "type": "text",
            "name": "IsProcessed",
            "span": 12,
            "disabled": true,
        }, {
            "name": "row",
            "span": 24
        }, {
            "label": "反馈内容",
            "placeholder": "反馈内容",
            "type": "textarea",
            "name": "FeedbackContent",
            "span": 24,
            "disabled": true,
        }, {
            "label": "反馈帐号",
            "placeholder": "反馈帐号",
            "type": "text",
            "name": "",
            "span": 12,
            "disabled": true,
        }, {
            "label": "手机号码",
            "placeholder": "手机号码",
            "type": "text",
            "name": "MobileNo",
            "span": 12,
            "disabled": true,
        }, {
            "name": "row",
            "span": 24
        }, {
            "label": "问题类型",
            "placeholder": "问题类型",
            "type": "text",
            "name": "QuestionType",
            "span": 12,
            "disabled": true,
        }, {
            "label": "游戏类型",
            "placeholder": "游戏类型",
            "type": "text",
            "name": "GameType",
            "span": 12,
            "disabled": true,
        }, {
            "name": "row",
            "span": 24
        }, {
            "label": "反馈日期",
            "placeholder": "反馈日期",
            "type": "text",
            "name": "FeedbackDate",
            "span": 12,
            "disabled": true,
        }, {
            "label": "反馈地址",
            "placeholder": "反馈地址",
            "type": "text",
            "name": "ClientIP",
            "span": 12,
            "disabled": true,
        }, {
            "name": "row",
            "span": 24
        }, {
            "label": "回复内容",
            "placeholder": "回复内容",
            "type": "textarea",
            "name": "RevertContent",
            "span": 24,
        }, {
            "name": "row",
            "span": 24
        }, {
            "label": "回复人",
            "placeholder": "回复人",
            "type": "text",
            "name": "RevertUserID",
            "span": 12,
            "disabled": true,
        }, {
            "label": "回复日期",
            "placeholder": "回复日期",
            "type": "timeRange",
            "name": "RevertDate",
            "span": 12,
            "disabled": true,
        }, {
            "name": "row",
            "span": 24
        }, {
            "label": "显示状态",
            "placeholder": "显示状态",
            "type": "select",
            "name": "Nullity",
            "options": [{
                value: '1',
                label: '禁用'
            }],
            "span": 12,
        }]
    }
}