export function popupForm() {
    return {
        "inline": true,
        "btnSpan": 6,
        "btns": [{
            "name": "query",
            "title": "设 置",
            "type": "success",
            "valid": false
        }],
        "formEle": [{
            "label": "弹窗类型",
            "placeholder": "请选择弹窗类型",
            "type": "select",
            "name": "",
            "options": [{
                value: '1',
                label: '免责声明'
            }, {
                value: '2',
                label: '系统公告'
            }, {
                value: '3',
                label: '开启推送提示'
            }, {
                value: '4',
                label: '实名认证'
            }, {
                value: '5',
                label: '活动大弹窗'
            }, {
                value: '6',
                label: '签到'
            }, {
                value: '7',
                label: '活动'
            }, {
                value: '8',
                label: '定时奖励'
            }],
            'multiple': true,
            "span": 6
        }, {
            "label": "弹窗频率",
            "placeholder": "请选择弹窗频率",
            "type": "select",
            "name": "",
            "options": [{
                value: '1',
                label: '仅首次启动APP弹出1次'
            }, {
                value: '2',
                label: '每次登录'
            }, {
                value: '3',
                label: '每天一次'
            }, {
                value: '4',
                label: '每周一次'
            }],
            'multiple': true,
            "span": 6
        }, {
            "label": "设备类型",
            "placeholder": "请选择设备类型",
            "type": "select",
            "name": "",
            "options": [{
                value: '0',
                label: '全部'
            }, {
                value: '1',
                label: 'Android'
            }, {
                value: '2',
                label: 'ios'
            }],
            "span": 6
        }, {
            "label": "账号类型",
            "placeholder": "请选择账号类型可见",
            "type": "select",
            "name": "",
            "options": [{
                value: '1',
                label: '微信帐号'
            }, {
                value: '2',
                label: 'QQ帐号'
            }, {
                value: '3',
                label: '手机帐号'
            }, {
                value: '4',
                label: '游客帐号'
            }, {
                value: '5',
                label: 'X渠道帐号'
            }],
            'multiple': true,
            "span": 6
        }, {
            "row": 24
        }, {
            "label": "充值区间",
            "placeholder": "请选择充值可见区间",
            "type": "select",
            "name": "",
            "options": [],
            "span": 6
        }, {
            "label": "图片",
            "placeholder": "请输入图片在服务器上的地址",
            "type": "text",
            "name": "",
            "span": 6
        }, {
            "label": "跳转页面",
            "placeholder": "请输入需要跳转的页面ID",
            "type": "text",
            "name": "",
            "span": 6
        }, {
            "label": "跳转链接",
            "placeholder": "请输入需要跳转链接",
            "type": "text",
            "name": "",
            "span": 6
        }, {
            "row": 24
        }, {
            "label": "内容",
            "placeholder": "请输入弹窗内容",
            "type": "textarea",
            "name": "",
            "rows": 4,
            "span": 24
        }, {
            "row": 24
        }, {
            "label": "选择时间",
            "placeholder": "请选择开始/结束时间",
            "type": "timeRange",
            "name": "",
            "span": 8
        }]
    }
}