export function summaryForm() {
    return {
        "inline": true,
        "btnSpan": 18,
        "btns": [{
            "name": "setUp",
            "title": "设 置",
            "valid": false
        }],
        "formEle": [{
            "label": "title",
            "placeholder": "title",
            "type": "text",
            "name": "title",
            "span": 6
        }, {
            "label": "titleUrl",
            "placeholder": "titleUrl",
            "type": "text",
            "name": "titleUrl",
            "span": 6
        }, {
            "label": "site",
            "placeholder": "site",
            "type": "text",
            "name": "site",
            "span": 6
        }, {
            "label": "siteUrl",
            "placeholder": "siteUrl",
            "type": "text",
            "name": "siteUrl",
            "span": 6
        }, {
            "label": "text",
            "placeholder": "text",
            "type": "text",
            "name": "text",
            "span": 6
        }, {
            "label": "imagePath",
            "placeholder": "imagePath",
            "type": "text",
            "name": "imagePath",
            "span": 6
        }, {
            "label": "imageUrl",
            "placeholder": "imageUrl",
            "type": "text",
            "name": "imageUrl",
            "span": 6
        }, {
            "label": "comment",
            "placeholder": "comment",
            "type": "text",
            "name": "comment",
            "span": 6
        }, {
            "label": "url",
            "placeholder": "url",
            "type": "text",
            "name": "url",
            "span": 6
        }, {
            "label": "mediaType",
            "placeholder": "mediaType",
            "type": "text",
            "name": "mediaType",
            "span": 6
        }, {
            "label": "shareTo",
            "placeholder": "shareTo",
            "type": "text",
            "name": "shareTo",
            "span": 6
        }, {
            "label": "thumbImage",
            "placeholder": "thumbImage",
            "type": "text",
            "name": "thumbImage",
            "span": 6
        }, {
            "label": "thumbSize",
            "placeholder": "thumbSize",
            "type": "text",
            "name": "thumbSize",
            "span": 6
        }, {
            "label": "videoPath",
            "placeholder": "videoPath",
            "type": "text",
            "name": "videoPath",
            "span": 6
        }]
    }
}