export function permits() {
    return [{
        title: '首页',
        permit: true,
        permit_id: 40,
        sub: [{
            title: '我的桌面',
            name: '我的桌面',
            to: '/',
            permit: true,
            permit_id: 41
        }]
    }, {
        title: '游戏总览',
        permit: true,
        permit_id: 1,
        sub: [{
            title: '日报汇总',
            name: 'summary',
            to: '/global/summary',
            permit: true,
            permit_id: 2
        }, {
            title: '实时数据',
            name: 'real_time',
            to: '/global/real_time',
            permit: true,
            permit_id: 3
        }]
    }, {
        title: '数据分析',
        permit: true,
        permit_id: 4,
        sub: [{
            title: '用户分析',
            name: 'user_analysis',
            to: '/analyse/user_analysis',
            permit: true,
            permit_id: 5
        }, {
            title: '看牌抢庄',
            name: 'look_cards',
            to: '/analyse/look_cards',
            permit: true,
            permit_id: 6
        }, {
            title: '小游戏',
            name: 'mini_game',
            to: '/analyse/mini_game',
            permit: true,
            permit_id: 7
        }, {
            title: '排行榜',
            name: 'rank',
            to: '/analyse/rank',
            permit: true,
            permit_id: 8
        }, {
            title: '付费分析',
            name: 'pay_analysis',
            to: '/analyse/pay_analysis',
            permit: true,
            permit_id: 9
        }, {
            title: '任务分析',
            name: 'miniactivity',
            to: '/analyse/miniactivity',
            permit: true,
            permit_id: 51
        }, {
            title: '埋点数据',
            name: 'buried_point',
            to: '/analyse/buried_point',
            permit: true,
            permit_id: 49
        }, {
            title: '产出消耗',
            name: 'product_consume',
            to: '/analyse/product_consume',
            permit: true,
            permit_id: 44
        }, {
            title: '道具购买分析',
            name: 'buy_item',
            to: '/analyse/buy_item',
            permit: true,
            permit_id: 10
        }]
    }, {
        title: '用户管理',
        permit: true,
        permit_id: 11,
        sub: [{
            title: '用户信息',
            name: 'user_info',
            to: '/users/user_info',
            permit: true,
            permit_id: 12
        }, {
            title: '封禁管理',
            name: 'risk_manage',
            to: '/users/risk_manage',
            permit: true,
            permit_id: 13
        }, {
            title: '黑名单',
            name: 'blacklist',
            to: '/users/blacklist',
            permit: true,
            permit_id: 14
        }, {
            title: '内部帐号',
            name: 'int_account',
            to: '/users/int_account',
            permit: true,
            permit_id: 15
        }]
    }, {
        title: '渠道管理',
        permit: true,
        permit_id: 16,
        sub: [{
            title: '渠道商管理',
            name: 'channel_master',
            to: '/channel/channel_master',
            permit: true,
            permit_id: 18
        }, {
            title: '渠道分析',
            name: 'channel_analyze',
            to: '/channel/channel_analyze',
            permit: true,
            permit_id: 17
        }, {
            title: '渠道管理',
            name: 'channel_config',
            to: '/channel/channel_config',
            permit: true,
            permit_id: 19
        }]
    }, {
        title: '支付管理',
        permit: true,
        permit_id: 20,
        sub: [{
            title: '支付订单',
            name: 'payment_order',
            to: '/pay/payment_order',
            permit: true,
            permit_id: 21
        }, {
            title: '充值统计',
            name: 'pay_statistics',
            to: '/pay/pay_statistics',
            permit: true,
            permit_id: 55
        }]
    }, {
        title: '兑换管理',
        permit: true,
        permit_id: 22,
        sub: [{
            title: '数值表',
            name: 'numeric_table',
            to: '/exchange/numeric_table',
            permit: true,
            permit_id: 54
        }, {
            title: '兑换审核',
            name: 'exchange_audit',
            to: '/exchange/exchange_audit',
            permit: true,
            permit_id: 23
        }, {
            title: '兑换记录',
            name: 'exchange_record',
            to: '/exchange/exchange_record',
            permit: true,
            permit_id: 24
        }, {
            title: '卡密管理',
            name: 'kami',
            to: '/exchange/kami',
            permit: true,
            permit_id: 50
        }]
    }, {
        title: '客服工具',
        permit: true,
        permit_id: 42,
        sub: [{
            title: '走马灯',
            name: 'notice',
            to: '/kefu/notice',
            permit: true,
            permit_id: 32
        }, {
            title: '系统邮件',
            name: 'mail',
            to: '/kefu/mail',
            permit: true,
            permit_id: 33
        }, {
            title: '问题反馈',
            name: 'feedback',
            to: '/kefu/feedback',
            permit: true,
            permit_id: 34
        }, {
            title: '举报管理',
            name: 'report',
            to: '/kefu/report',
            permit: true,
            permit_id: 52
        }, {
            title: '实名认证',
            name: 'realname',
            to: '/kefu/realname',
            permit: true,
            permit_id: 53
        }]
    }, {
        title: '鹰眼系统',
        permit: true,
        permit_id: 47,
        sub: [{
            title: '鹰眼1(测试)',
            name: 'eye',
            to: '/hawkeye/eye',
            permit: true,
            permit_id: 48
        }]
    }, {
        title: '游戏配置',
        permit: true,
        permit_id: 25,
        sub: [{
            title: '系统表推送',
            name: 'json_push',
            to: '/deploy/json_push',
            permit: true,
            permit_id: 37
        }, {
            title: '离线推送',
            name: 'push',
            to: '/deploy/push',
            permit: true,
            permit_id: 46
        }, {
            title: 'AI配置',
            name: 'robot',
            to: '/deploy/robot',
            permit: true,
            permit_id: 43
        }, {
            title: '比赛配置',
            name: 'match_config',
            to: '/deploy/match_config',
            permit: true,
            permit_id: 26
        }, {
            title: '看牌抢庄配置',
            name: 'lookCards_config',
            to: '/deploy/lookCards_config',
            permit: true,
            permit_id: 27
        }, {
            title: '任务配置',
            name: 'task_config',
            to: '/deploy/task_config',
            permit: true,
            permit_id: 28
        }, {
            title: '活动配置',
            name: 'activity_config',
            to: '/deploy/activity_config',
            permit: true,
            permit_id: 29
        }, {
            title: '弹窗配置',
            name: 'popup_config',
            to: '/deploy/popup_config',
            permit: true,
            permit_id: 30
        }, {
            title: '防沉迷系统',
            name: 'indulge',
            to: '/deploy/indulge',
            permit: true,
            permit_id: 45
        }, {
            title: '商城订单配置',
            name: 'shop_config',
            to: '/deploy/shop_config',
            permit: true,
            permit_id: 31
        }, {
            title: '游戏屏蔽',
            name: 'shield',
            to: '/deploy/shield',
            permit: true,
            permit_id: 56
        }]
    }, {
        title: '后台管理',
        permit: true,
        permit_id: 35,
        sub: [{
            title: '权限/帐号管理',
            name: 'account',
            to: '/cms/account',
            permit: true,
            permit_id: 36
        }, {
            title: '操作日志',
            name: 'loger',
            to: '/cms/loger',
            permit: true,
            permit_id: 38
        }, {
            title: '团队原则',
            name: 'team',
            to: '/cms/team',
            permit: true,
            permit_id: 39
        }]
    }];
}
